FROM node:18-alpine

WORKDIR /home/node

# Copia las dependencias y realiza la instalación primero
COPY package.json . 
COPY yarn.lock .

# Instala las dependencias antes de copiar el código
RUN yarn install

# Luego copia el código fuente
COPY . .

EXPOSE 3000

CMD [ "yarn", "start" ]